services:
  mosquitto:
    build: ./mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"

  zigbee2mqtt:
    build: ./zigbee2mqtt
    restart: unless-stopped
    group_add:
      - "dialout"                     
    depends_on:
      - mosquitto
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "8080:8080"
    volumes:
      - /run/udev:/run/udev:ro

  homelander:
    build:
      context: .
      dockerfile: ./src/homelander/Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_ADDRESS=mosquitto